Repository hmcts/opal-fines-service, pull requests merged in 2025-04, with the labels that each got.

#774 neater test reporting in jenkins
  Jenkinsfile_CNP
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/opal/LegacyTestRunner.java
  src/functionalTest/java/uk/gov/hmcts/opal/OpalTestRunner.java
  src/functionalTest/java/uk/gov/hmcts/opal/SmokeTestRunner.java
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-774

#787 CVE resolution
  build.gradle
  src/test/java/uk/gov/hmcts/opal/controllers/advice/GlobalExceptionHandlerTest.java
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-787

#779 feat(reporting): add HTML summary generation for test results
  Jenkinsfile_CNP
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/opal/scripts/TestReportSummaryGenerator.java
  src/functionalTest/java/uk/gov/hmcts/opal/scripts/script.js
  src/functionalTest/java/uk/gov/hmcts/opal/scripts/styles.css
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-779

#786 Adding display names to integration tests for better clarity
  src/integrationTest/java/uk/gov/hmcts/opal/controllers/BusinessUnitControllerIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/opal/controllers/CourtControllerIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/opal/controllers/DefendantAccountControllerIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerTransientErrorsIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/opal/controllers/EnforcerControllerIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/opal/controllers/GetWelcomeTest.java
  src/integrationTest/java/uk/gov/hmcts/opal/controllers/LocalJusticeAreaControllerIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/opal/controllers/MajorCreditorControllerIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/opal/controllers/OffenceControllerIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/opal/controllers/ResultControllerIntegrationTest.java
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-786

#777 PO-1276 Chi added script to create enforcer_allocations table
  src/main/resources/db/migration/allEnvs/V20250409_305__enforcer_allocations.sql
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-777

#791 setup nightly pipeline to run tests
  Jenkinsfile_nightly
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-791

#792 re-order nightly pipeline execution... maybe
  Jenkinsfile_nightly
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-792

#793 re-order nightly pipeline execution
  Jenkinsfile_nightly
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-793

#794 fix nightly pipeline
  Jenkinsfile_nightly
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-794

#795 fix nightly pipeline
  Jenkinsfile_nightly
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-795

#807 PO-1446: Add Schemas for various Reference Datas
  src/functionalTest/java/uk/gov/hmcts/opal/steps/offences/SearchOffencesRequestStepDef.java
  src/functionalTest/resources/features/opalMode/manualAccountCreation/offences/PO-614_newFieldsInOffenceAPI.feature
  src/functionalTest/resources/features/opalMode/manualAccountCreation/offences/PO-926_offencesSearchApi.feature
  src/integrationTest/java/uk/gov/hmcts/opal/controllers/BusinessUnitControllerIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/opal/controllers/CourtControllerIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/opal/controllers/LocalJusticeAreaControllerIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/opal/controllers/MajorCreditorControllerIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/opal/controllers/OffenceControllerIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/opal/controllers/ResultControllerIntegrationTest.java
  src/main/java/uk/gov/hmcts/opal/dto/search/OffenceSearchDto.java
  src/main/java/uk/gov/hmcts/opal/entity/projection/OffenceReferenceData.java
  src/main/java/uk/gov/hmcts/opal/service/opal/OffenceService.java
  src/main/resources/jsonSchemas/getBusinessUnitsRefDataResponse.json
  src/main/resources/jsonSchemas/getCourtsRefDataResponse.json
  src/main/resources/jsonSchemas/getLJARefDataResponse.json
  src/main/resources/jsonSchemas/getMajorCredRefDataResponse.json
  src/main/resources/jsonSchemas/getOffencesRefDataResponse.json
  src/main/resources/jsonSchemas/getResultsRefDataResponse.json
  src/main/resources/jsonSchemas/postCourtsSearchResponse.json
  src/main/resources/jsonSchemas/postOffencesSearchResponse.json
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-807
