Repository hmcts/opal-fines-service, pull requests merged in 2025-09, with the labels that each got.

#1119 Schema rework
  src/main/resources/jsonSchemas/legacy/addNoteLegacyRequest.json
  src/main/resources/jsonSchemas/legacy/addNoteLegacyResponse.json
  src/main/resources/jsonSchemas/legacy/common-objects/accountActivityNoteLegacy.json
  src/main/resources/jsonSchemas/legacy/common-objects/individualDetailsLegacy.json
  src/main/resources/jsonSchemas/legacy/common-objects/noteLegacy.json
  src/main/resources/jsonSchemas/legacy/common-objects/paymentTermsLegacy.json
  src/main/resources/jsonSchemas/legacy/common-objects/paymentTermsSummaryLegacy.json
  src/main/resources/jsonSchemas/opal/common-objects/accountActivityNote.json
  src/main/resources/jsonSchemas/opal/common-objects/individualDetails.json
  src/main/resources/jsonSchemas/opal/common-objects/instalmentPeriod.json
  src/main/resources/jsonSchemas/opal/common-objects/note.json
  src/main/resources/jsonSchemas/opal/common-objects/paymentTerms.json
  src/main/resources/jsonSchemas/opal/common-objects/paymentTermsSummary.json
  src/main/resources/jsonSchemas/opal/defendant-account/addNoteRequest.json
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-1119

#1125 Schedule renovate to run on Wednesdays only.
  .github/renovate.json
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-1125

#1126 PO-1666_PO-1677 - Added database procedures for auditing amendment lists (initialise and finalise)
  src/dbUnitTest/auditFinaliseTest/p_audit_finalise_unit_tests.sql
  src/dbUnitTest/auditInitialiseTest/p_audit_initialise_unit_tests.sql
  src/main/resources/db/migration/allEnvs/V20250902_395__p_audit_initialise.sql
  src/main/resources/db/migration/allEnvs/V20250902_396__p_audit_finalise.sql
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-1126

#1130 make defendant_account_id and version required in response
  src/main/resources/jsonSchemas/legacy/updateDefendantAccountLegacyResponse.json
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-1130

#1095 PO-985: Add GET /defendant-accounts/{id}/header-summary (Opal) — new …
  src/integrationTest/java/uk/gov/hmcts/opal/controllers/DefendantAccountsControllerIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/opal/controllers/OpalDefendantAccountsIntegrationTest.java
  src/integrationTest/resources/db/insertData/delete_from_defendant_accounts.sql
  src/integrationTest/resources/db/insertData/insert_into_defendant_accounts.sql
  src/main/java/uk/gov/hmcts/opal/controllers/DefendantAccountController.java
  src/main/java/uk/gov/hmcts/opal/controllers/LoggingExceptionResolver.java
  src/main/java/uk/gov/hmcts/opal/dto/DefendantAccountHeaderSummary.java
  src/main/java/uk/gov/hmcts/opal/dto/common/PartyDetails.java
  src/main/java/uk/gov/hmcts/opal/dto/response/GetHeaderSummaryResponse.java
  src/main/java/uk/gov/hmcts/opal/dto/response/GetResponse.java
  src/main/java/uk/gov/hmcts/opal/entity/DefendantAccountHeaderViewEntity.java
  src/main/java/uk/gov/hmcts/opal/repository/DefendantAccountHeaderViewRepository.java
  src/main/java/uk/gov/hmcts/opal/service/DefendantAccountService.java
  src/main/java/uk/gov/hmcts/opal/service/legacy/LegacyDefendantAccountService.java
  src/main/java/uk/gov/hmcts/opal/service/opal/OpalDefendantAccountService.java
  src/main/java/uk/gov/hmcts/opal/service/proxy/DefendantAccountServiceProxy.java
  src/main/resources/jsonSchemas/opal/defendant-account/getDefendantAccountHeaderSummaryResponse.json
  src/test/java/uk/gov/hmcts/opal/controllers/DefendantAccountControllerTest.java
  src/test/java/uk/gov/hmcts/opal/service/DefendantAccountServiceTest.java
  src/test/java/uk/gov/hmcts/opal/service/legacy/LegacyDefendantAccountServiceTest.java
  src/test/java/uk/gov/hmcts/opal/service/opal/OpalDefendantAccountServiceTest.java
  src/test/java/uk/gov/hmcts/opal/service/proxy/DefendantAccountServiceProxyTest.java
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-1095

#1133 remove note_id from addNoteLegacyResponse.json
  src/main/resources/jsonSchemas/legacy/addNoteLegacyResponse.json
  src/main/resources/jsonSchemas/legacy/getDefendantAccountHeaderSummaryLegacyResponse.json
  src/main/resources/jsonSchemas/opal/defendant-account/getDefendantAccountHeaderSummaryResponse.json
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-1133

#1134 Change references to correct common object for parties
  src/main/resources/jsonSchemas/legacy/getDefendantAccountPartyLegacyResponse.json
  src/main/resources/jsonSchemas/legacy/replaceDefendantAccountPartyLegacyRequest.json
  src/main/resources/jsonSchemas/legacy/replaceDefendantAccountPartyLegacyResponse.json
  src/main/resources/jsonSchemas/opal/defendant-account/getDefendantAccountPartyResponse.json
  src/main/resources/jsonSchemas/opal/defendant-account/replaceDefendantAccountPartyRequest.json
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-1134

#1131 MAC Phase 4
  src/dbUnitTest/createAccountNotesTest/p_create_account_notes_unit_tests.sql
  src/dbUnitTest/createAccountNotesTest/p_create_account_notes_unit_tests.txt
  src/dbUnitTest/createDefendantAccountTest/p_create_defendant_account_unit_tests_v3_2.sql
  src/dbUnitTest/createDefendantAccountTest/p_create_defendant_account_unit_tests_v3_2.txt
  src/dbUnitTest/createDefendantAccountTest/p_create_defendant_account_unit_tests_v3_3.sql
  src/dbUnitTest/createDefendantAccountTest/p_create_defendant_account_unit_tests_v3_3.txt
  src/dbUnitTest/createDefendantAccountTest/p_create_defendant_account_unit_tests_v3_4.sql
  src/dbUnitTest/createDefendantAccountTest/p_create_defendant_account_unit_tests_v3_4.txt
  src/dbUnitTest/createDefendantAccountTest/p_create_defendant_account_unit_tests_v3_5.sql
  src/dbUnitTest/createDefendantAccountTest/p_create_defendant_account_unit_tests_v3_5.txt
  src/dbUnitTest/createDefendantAccountTest/p_create_defendant_account_unit_tests_v3_6.sql
  src/dbUnitTest/createDefendantAccountTest/p_create_defendant_account_unit_tests_v3_6.txt
  src/dbUnitTest/createPaymentTermsTest/p_create_payment_terms_unit_tests.sql
  src/dbUnitTest/createPaymentTermsTest/p_create_payment_terms_unit_tests.txt
  src/main/resources/db/migration/allEnvs/V20250904_397__create_imposition_category_item_number.sql
  src/main/resources/db/migration/allEnvs/V20250904_398__populate_imposition_category_item_number.sql
  src/main/resources/db/migration/allEnvs/V20250904_399__p_get_creditor_account.sql
  src/main/resources/db/migration/allEnvs/V20250904_400__p_create_fp_offences.sql
  src/main/resources/db/migration/allEnvs/V20250904_401__alter_impositions.sql
  src/main/resources/db/migration/allEnvs/V20250904_402__p_create_impositions.sql
  src/main/resources/db/migration/allEnvs/V20250904_403__add_version_number_to_creditor_accounts.sql
  src/main/resources/db/migration/allEnvs/V20250904_404__p_create_minor_creditor.sql
  src/main/resources/db/migration/allEnvs/V20250904_405__p_create_payment_terms.sql
  src/main/resources/db/migration/allEnvs/V20250904_406__p_create_defendant_account.sql
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-1131

#1128 Po 1716 get defendant account payment terms
  src/functionalTest/java/uk/gov/hmcts/opal/steps/RefDataStepDef.java
  src/functionalTest/java/uk/gov/hmcts/opal/steps/draftaccount/DraftAccountGetSteps.java
  src/integrationTest/java/uk/gov/hmcts/opal/controllers/DefendantAccountsControllerIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/opal/controllers/LegacyDefendantAccountsIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/opal/controllers/OpalDefendantAccountsIntegrationTest.java
  src/integrationTest/resources/db/insertData/insert_into_defendant_accounts.sql
  src/main/java/uk/gov/hmcts/opal/controllers/DefendantAccountController.java
  src/main/java/uk/gov/hmcts/opal/dto/GetDefendantAccountPaymentTermsResponse.java
  src/main/java/uk/gov/hmcts/opal/dto/InstalmentPeriod.java
  src/main/java/uk/gov/hmcts/opal/dto/PaymentTerms.java
  src/main/java/uk/gov/hmcts/opal/dto/PaymentTermsType.java
  src/main/java/uk/gov/hmcts/opal/dto/PostedDetails.java
  src/main/java/uk/gov/hmcts/opal/entity/DefendantAccountEntity.java
  src/main/java/uk/gov/hmcts/opal/entity/PaymentTermsEntity.java
  src/main/java/uk/gov/hmcts/opal/repository/DefendantAccountPaymentTermsRepository.java
  src/main/java/uk/gov/hmcts/opal/service/DefendantAccountService.java
  src/main/java/uk/gov/hmcts/opal/service/iface/DefendantAccountServiceInterface.java
  src/main/java/uk/gov/hmcts/opal/service/legacy/LegacyDefendantAccountService.java
  src/main/java/uk/gov/hmcts/opal/service/opal/OpalDefendantAccountService.java
  src/main/java/uk/gov/hmcts/opal/service/proxy/DefendantAccountServiceProxy.java
  src/test/java/uk/gov/hmcts/opal/service/DefendantAccountServiceTest.java
  src/test/java/uk/gov/hmcts/opal/service/opal/OpalDefendantAccountServiceTest.java
  src/test/java/uk/gov/hmcts/opal/service/proxy/DefendantAccountServiceProxyTest.java
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-1128

#1129 Added InteliJ checkstyle config
  .idea/codeStyles/Project.xml
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-1129

#1144 Add renovate configuration options to curtail some aggressive upgrades.
  .github/renovate.json
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-1144

#1148 fix enum value, remove space
  src/main/resources/jsonSchemas/legacy/common-objects/noteLegacy.json
  src/main/resources/jsonSchemas/opal/common-objects/note.json
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-1148

#1152 tr-895
  charts/opal-fines-service/values.stg.template.yaml
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-1152

#1160 Added ITHC terraform file
  infrastructure/ithc.tfvars
Labels: ns:opal, prd:opal, stg/no-changes, rel:opal-fines-service-pr-1160

#1161 Defendant account summary xsd
  src/main/resources/xsd/legacy/addNote/add_note_request.xsd
  src/main/resources/xsd/legacy/addNote/add_note_response.xsd
  src/main/resources/xsd/legacy/common-objects/account_status_reference.xsd
  src/main/resources/xsd/legacy/common-objects/address_details.xsd
  src/main/resources/xsd/legacy/common-objects/business_unit_summary.xsd
  src/main/resources/xsd/legacy/common-objects/comments_and_notes.xsd
  src/main/resources/xsd/legacy/common-objects/enforcement_override.xsd
  src/main/resources/xsd/legacy/common-objects/enforcement_override_result_reference.xsd
  src/main/resources/xsd/legacy/common-objects/enforcement_status_summary.xsd
  src/main/resources/xsd/legacy/common-objects/enforcer_reference.xsd
  src/main/resources/xsd/legacy/common-objects/error_response.xsd
  src/main/resources/xsd/legacy/common-objects/individual_aliases.xsd
  src/main/resources/xsd/legacy/common-objects/individual_aliases_element.xsd
  src/main/resources/xsd/legacy/common-objects/individual_details.xsd
  src/main/resources/xsd/legacy/common-objects/language.xsd
  src/main/resources/xsd/legacy/common-objects/language_preferences.xsd
  src/main/resources/xsd/legacy/common-objects/last_enforcement_action.xsd
  src/main/resources/xsd/legacy/common-objects/lja_reference.xsd
  src/main/resources/xsd/legacy/common-objects/note.xsd
  src/main/resources/xsd/legacy/common-objects/organisation_aliases.xsd
  src/main/resources/xsd/legacy/common-objects/organisation_aliases_element.xsd
  src/main/resources/xsd/legacy/common-objects/organisation_details.xsd
  src/main/resources/xsd/legacy/common-objects/party_details.xsd
  src/main/resources/xsd/legacy/common-objects/payment_state_summary.xsd
  src/main/resources/xsd/legacy/common-objects/payment_terms_summary.xsd
  src/main/resources/xsd/legacy/common-objects/simple_type.xsd
  src/main/resources/xsd/legacy/getDefendantAccountAtAGlance/get_defendant_account_at_a_glance_response.xsd
  src/main/resources/xsd/legacy/getDefendantAccountAtAGlance/get_defendant_account_request.xsd
  src/main/resources/xsd/legacy/getDefendantAccountHeaderSummary/get_defendant_account_header_summary_response.xsd
  src/main/resources/xsd/legacy/getDefendantAccountHeaderSummary/get_defendant_account_request.xsd
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-1161

#1158 PO-1788 added new permission Enter Enforcement and assigned permissio…
  src/main/resources/db/migration/allEnvs/V20250911_412__new_perm_enter_enforcement.sql
  src/main/resources/db/migration/allEnvs/V20250911_413__assign_enter_enforcement_permissions.sql
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-1158

#1169 Fixed issue with getDefendantAccountEnforcementStatusLegacyResponse.json
  src/main/resources/jsonSchemas/legacy/getDefendantAccountEnforcementStatusLegacyResponse.json
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-1169

#1177 Tidied up some code / added comment for temp overrides
  build.gradle
  charts/opal-fines-service/Chart.yaml
  charts/opal-fines-service/values.yaml
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-1177

#1195 Remove direct dependency management of netty packages was due to CVE.
  build.gradle
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-1195

#1179 P0-2117 e tag tests
  src/functionalTest/java/uk/gov/hmcts/opal/steps/draftaccount/DraftAccountDeleteSteps.java
  src/functionalTest/java/uk/gov/hmcts/opal/steps/draftaccount/DraftAccountPostSteps.java
  src/functionalTest/java/uk/gov/hmcts/opal/utils/DataCleanUp.java
  src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/deleteDraftAccount/PO-2117_deleteDraftAccount.feature
  src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/getDraftAccountsMulti/PO-829_getDraftAccountsAuthorization.feature
  src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerTransientErrorsIntegrationTest.java
Labels: ns:opal, prd:opal, rel:opal-fines-service-pr-1179

#1139 PO-2117: Return ETag for versioned Entities, and expect If-Match for updates
  src/functionalTest/java/uk/gov/hmcts/opal/steps/BaseStepDef.java
  src/functionalTest/java/uk/gov/hmcts/opal/steps/draftaccount/DraftAccountDeleteSteps.java
  src/functionalTest/java/uk/gov/hmcts/opal/steps/draftaccount/DraftAccountPatchSteps.java
  src/functionalTest/java/uk/gov/hmcts/opal/steps/draftaccount/DraftAccountPostSteps.java
  src/functionalTest/java/uk/gov/hmcts/opal/steps/draftaccount/DraftAccountPutSteps.java
  src/functionalTest/java/uk/gov/hmcts/opal/utils/DataCleanUp.java
  src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/PO-745_patchDraftAccount.feature
  src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/PO-747_patchDraftAccountErrorHandling.feature
  src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/PO-831_patchDraftAccountAuthorisation.feature
  src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/deleteDraftAccount/PO-2117_deleteDraftAccount.feature
  src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/getDraftAccountsMulti/PO-606_getDraftAccounts.feature
  src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/getDraftAccountsMulti/PO-829_getDraftAccountsAuthorization.feature
  src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/replaceDraftAccount/PO-746_putDraftAccount.feature
  src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/replaceDraftAccount/PO-749_putDraftAccountErrorHandling.feature
  src/functionalTest/resources/features/opalMode/manualAccountCreation/draftAccounts/replaceDraftAccount/PO-830_putDraftAccountAuthorisation.feature
  src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerTransientErrorsIntegrationTest.java
  src/main/java/uk/gov/hmcts/opal/controllers/DraftAccountController.java
  src/main/java/uk/gov/hmcts/opal/controllers/advice/GlobalExceptionHandler.java
  src/main/java/uk/gov/hmcts/opal/dto/DefendantAccountHeaderSummary.java
  src/main/java/uk/gov/hmcts/opal/dto/DraftAccountResponseDto.java
  src/main/java/uk/gov/hmcts/opal/dto/DraftAccountSummaryDto.java
  src/main/java/uk/gov/hmcts/opal/dto/ReplaceDraftAccountRequestDto.java
  src/main/java/uk/gov/hmcts/opal/dto/UpdateDraftAccountRequestDto.java
  src/main/java/uk/gov/hmcts/opal/dto/response/GetHeaderSummaryResponse.java
  src/main/java/uk/gov/hmcts/opal/dto/response/GetResponse.java
  src/main/java/uk/gov/hmcts/opal/mapper/DraftAccountMapper.java
  src/main/java/uk/gov/hmcts/opal/service/DraftAccountService.java
  src/main/java/uk/gov/hmcts/opal/service/opal/OpalDefendantAccountService.java
  src/main/java/uk/gov/hmcts/opal/service/opal/jpa/DraftAccountTransactions.java
  src/main/java/uk/gov/hmcts/opal/util/HttpUtil.java
  src/main/java/uk/gov/hmcts/opal/util/VersionUtils.java
  src/test/java/uk/gov/hmcts/opal/controllers/DefendantAccountControllerTest.java
  src/test/java/uk/gov/hmcts/opal/controllers/DraftAccountControllerTest.java
  src/test/java/uk/gov/hmcts/opal/controllers/advice/GlobalExceptionHandlerTest.java
  src/test/java/uk/gov/hmcts/opal/service/DraftAccountServiceTest.java
  src/test/java/uk/gov/hmcts/opal/service/opal/jpa/DraftAccountTransactionsTest.java
  src/test/java/uk/gov/hmcts/opal/util/VersionUtilsTest.java
Labels: ns:opal, prd:opal, enable_keep_helm, rel:opal-fines-service-pr-1139
